# fly.toml app configuration file generated for crowd-spot on 2023-09-02T16:35:19+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crowd-spot"
primary_region = "syd"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
